# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: us_population.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13us_population.proto\"w\n\nPopulation\x12\x11\n\tid_nation\x18\x01 \x01(\t\x12\x0e\n\x06nation\x18\x02 \x01(\t\x12\x0f\n\x07id_year\x18\x03 \x01(\x05\x12\x0c\n\x04year\x18\x04 \x01(\t\x12\x12\n\npopulation\x18\x05 \x01(\x05\x12\x13\n\x0bslug_nation\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'us_population_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POPULATION']._serialized_start=23
  _globals['_POPULATION']._serialized_end=142
# @@protoc_insertion_point(module_scope)
